/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 检查 API 进程存活 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 检查完整依赖就绪状态 */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取账号功能与当前登录状态 */
        get: operations["getAuthState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 邮箱密码注册并认领当前匿名数据 */
        post: operations["registerAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 邮箱密码登录并认领当前匿名数据 */
        post: operations["loginAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退出登录并旋转匿名身份 */
        post: operations["logoutAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新显示名称 */
        patch: operations["updateAccountProfile"];
        trace?: never;
    };
    "/api/v1/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 校验当前密码后修改密码 */
        post: operations["changeAccountPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出当前匿名用户的会话 */
        get: operations["listSessions"];
        put?: never;
        /** 创建匿名产品会话 */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        /** 读取一个产品会话 */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发送消息并启动初筛或改单 run */
        post: operations["createMessageRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/requirement": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 完整替换待确认需求
         * @description 只允许 requirement_ready;请求体为完整替换而非 merge patch。
         */
        patch: operations["replacePendingRequirement"];
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/requirement/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 确认需求并启动生成 run */
        post: operations["confirmRequirement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /** 读取后台 run 状态 */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /** 读取自己的运行反馈 */
        get: operations["getRunFeedback"];
        put?: never;
        /**
         * 提交或修改已结束运行的负反馈
         * @description 同一运行只保留一份反馈；相同内容重复提交不重复创建，修改原因不更换证据。反馈不等于已批准的评估标准答案。
         */
        post: operations["submitRunFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: {
                /** @description SSE 重连游标;从其后一条事件开始。 */
                "Last-Event-ID"?: string;
            };
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /** 订阅并重放 run 事件 */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/builds": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        /** 列出会话的配置版本 */
        get: operations["listBuilds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/builds/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        /** 读取聚合配置版本 */
        get: operations["getBuild"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/diff": {
        parameters: {
            query: {
                from: number;
                to: number;
            };
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        /** 比较任意两个配置版本 */
        get: operations["getBuildDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/builds/{version}/export.md": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        /** 下载一个版本的 Markdown */
        get: operations["exportBuildMarkdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/builds/{version}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        /** 列出当前用户对固定版本创建过的分享 */
        get: operations["listBuildShares"];
        put?: never;
        /** 创建固定版本的只读分享 */
        post: operations["createBuildShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/builds/{version}/shares/{share_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
                share_id: components["parameters"]["ShareID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 按所有者分享 ID 撤销旧链接 */
        delete: operations["revokeBuildShareById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shares/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 撤销当前用户拥有的分享 */
        delete: operations["revokeBuildShare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/shares/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        /** 公开读取一份只读配置 */
        get: operations["getPublicBuildShare"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/shares/{token}/export.md": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        /** 公开下载固定分享版本的 Markdown */
        get: operations["exportPublicBuildShareMarkdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            schema_version: 1;
            /** @constant */
            status: "ok";
        };
        Readiness: {
            /** @constant */
            schema_version: 1;
            /** @enum {string} */
            status: "ready" | "degraded" | "unavailable";
            dependencies: {
                /** @enum {string} */
                postgres: "ok" | "unavailable";
                /** @enum {string} */
                redis: "ok" | "degraded" | "unavailable";
                /** @enum {string} */
                buildsvc: "ok" | "unavailable";
                /** @enum {string} */
                auth?: "ok" | "unavailable";
            };
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
            /** @enum {string} */
            code: "invalid_request" | "not_found" | "session_busy" | "invalid_session_phase" | "schema_validation_failed" | "upstream_unavailable" | "context_expired" | "run_timeout" | "run_interrupted" | "generation_failed" | "events_expired" | "internal_error" | "auth_disabled" | "auth_invalid_credentials" | "auth_email_exists" | "auth_weak_password" | "auth_session_expired" | "auth_unavailable";
            request_id: string;
        } & {
            [key: string]: unknown;
        };
        Account: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** Format: date-time */
            created_at: string;
        };
        AuthState: {
            /** @constant */
            schema_version: 1;
            enabled: boolean;
            authenticated: boolean;
            account: components["schemas"]["Account"] | null;
            claimed_session_count: number;
        };
        RegisterRequest: {
            /** @constant */
            schema_version: 1;
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
        };
        LoginRequest: {
            /** @constant */
            schema_version: 1;
            /** Format: email */
            email: string;
            password: string;
        };
        ProfileRequest: {
            /** @constant */
            schema_version: 1;
            display_name: string;
        };
        PasswordChangeRequest: {
            /** @constant */
            schema_version: 1;
            current_password: string;
            new_password: string;
            confirm_password: string;
        };
        /** @enum {string} */
        SessionPhase: "collecting" | "requirement_ready" | "building" | "ready" | "changing" | "error";
        SessionSummary: {
            /** @constant */
            schema_version: 1;
            id: string;
            title: string;
            phase: components["schemas"]["SessionPhase"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version_count: number;
        };
        Session: components["schemas"]["SessionSummary"] & {
            messages: components["schemas"]["Message"][];
            pending_requirement: components["schemas"]["RequirementSpec"] | null;
            active_run: components["schemas"]["Run"] | null;
            last_error: components["schemas"]["Problem"] | null;
            recovery_phase: ("collecting" | "requirement_ready" | "ready") | null;
            degraded: boolean;
        };
        Message: {
            /** @constant */
            schema_version: 1;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "user" | "assistant";
            content: string;
            run_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        FeedbackReason: "unnecessary_question" | "requirement_mismatch" | "configuration_issue" | "price_issue" | "unclear_explanation" | "other";
        FeedbackInput: {
            /** @constant */
            schema_version: 1;
            reason: components["schemas"]["FeedbackReason"];
            /** @description 选择 other 时必须填写非空说明 */
            comment?: string;
        };
        Feedback: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            reason: components["schemas"]["FeedbackReason"];
            comment: string;
            fingerprint: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        FeedbackResponse: {
            /** @constant */
            schema_version: 1;
            feedback: components["schemas"]["Feedback"] | null;
        };
        Run: {
            /** @constant */
            schema_version: 1;
            /** Format: uuid */
            id: string;
            session_id: string;
            /** @enum {string} */
            kind: "screening" | "build" | "change";
            /** @enum {string} */
            status: "running" | "succeeded" | "failed" | "interrupted";
            /** Format: date-time */
            started_at: string;
            finished_at?: string | null;
            error?: components["schemas"]["Problem"] | null;
            /** Format: uri-reference */
            events_url: string;
        };
        RequirementSpec: {
            /** @constant */
            schema_version: 1;
            budget_cny: number;
            /** @default 0.1 */
            budget_flex: number;
            use_case: {
                /** @enum {string} */
                type: "gaming" | "productivity" | "general";
                /** @default [] */
                titles: string[];
                /** @enum {string} */
                resolution?: "1080p" | "2K" | "4K";
                fps_target?: number;
            } & unknown;
            /**
             * @default any
             * @enum {string}
             */
            size_pref: "atx" | "matx" | "itx" | "any";
            /**
             * @default any
             * @enum {string}
             */
            noise_pref: "silent" | "normal" | "any";
            brand_pref?: {
                /**
                 * @default any
                 * @enum {string}
                 */
                cpu: "any" | "intel" | "amd";
                /**
                 * @default any
                 * @enum {string}
                 */
                gpu: "any" | "nvidia" | "amd";
            };
            /** @default [] */
            existing_parts: components["schemas"]["PartCategory"][];
            /**
             * @description 有已有件时必须明确；新增购买费用或整机参考总价。
             * @enum {string}
             */
            budget_basis?: "new_purchase" | "full_build";
            /** @description 每品类一个准确型号；仅 SSD 可多件，其余数量为 1。程序执行前精确绑定并锁定。 */
            owned_parts?: {
                category: components["schemas"]["PartCategory"];
                model: string;
                /** @default 1 */
                quantity: number;
            }[];
            /** @default [] */
            priority: components["schemas"]["PartCategory"][];
            /** @default  */
            notes: string;
        };
        /** @enum {string} */
        PartCategory: "cpu" | "gpu" | "motherboard" | "memory" | "ssd" | "psu" | "case" | "cooler";
        /** @example 6419.90 */
        Money: string;
        /**
         * @description 按响应时间动态计算；0–7 天 fresh，8–14 天 aging，超过 14 天 stale，缺少观察关联为 unknown。
         * @enum {string}
         */
        PriceFreshness: "fresh" | "aging" | "stale" | "unknown";
        PriceFreshnessSummary: {
            overall: components["schemas"]["PriceFreshness"];
            oldest_observed_date?: string | null;
            max_age_days?: number | null;
            fresh_count: number;
            aging_count: number;
            stale_count: number;
            unknown_count: number;
        };
        BuildSummary: {
            /** @constant */
            schema_version: 1;
            version: number;
            parent_version?: number | null;
            intent: string;
            total_cny: components["schemas"]["Money"];
            /** Format: date */
            snapshot_date: string;
            price_freshness?: components["schemas"]["PriceFreshness"];
            /** @enum {string} */
            overall_status: "pass" | "review" | "fail";
            /** Format: date-time */
            created_at: string;
        };
        PartLine: {
            /** @description 用户已有，无需购买；该行价格仍为参考价。 */
            owned?: boolean;
            category: components["schemas"]["PartCategory"];
            sku: string;
            name: string;
            quantity: number;
            unit_price_cny?: components["schemas"]["Money"] | null;
            subtotal_cny?: components["schemas"]["Money"] | null;
            rationale?: string;
            /** Format: date */
            price_observed_date?: string;
            price_freshness?: components["schemas"]["PriceFreshness"];
            /** @enum {string} */
            price_availability_basis?: "confirmed_stock" | "search_listing" | "unknown";
        };
        ValidationCheck: {
            rule_id: string;
            /** @enum {string} */
            outcome: "pass" | "fail" | "unknown";
            /** @enum {string} */
            severity: "none" | "warning" | "error";
            observed: {
                [key: string]: unknown;
            };
            missing_fields: string[];
            detail: string;
        };
        ValidationReport: {
            /** @enum {string} */
            overall_status: "pass" | "review" | "fail";
            checks: components["schemas"]["ValidationCheck"][];
        };
        Quote: {
            purchase_total_cny?: components["schemas"]["Money"];
            /** @enum {string} */
            budget_basis?: "new_purchase" | "full_build";
            /** Format: date */
            snapshot_date: string;
            total_cny: components["schemas"]["Money"];
            budget_cny: components["schemas"]["Money"];
            /** @description 预算减配置合计;正数表示剩余预算。 */
            budget_delta_cny: components["schemas"]["Money"];
            missing_count: number;
            missing_skus: string[];
            price_freshness?: components["schemas"]["PriceFreshnessSummary"];
        };
        BuildView: {
            /** @constant */
            schema_version: 1;
            summary: components["schemas"]["BuildSummary"];
            requirement: components["schemas"]["RequirementSpec"];
            parts: components["schemas"]["PartLine"][];
            quote: components["schemas"]["Quote"];
            validation: components["schemas"]["ValidationReport"];
            disclaimers: string[];
        };
        DiffLine: {
            category: components["schemas"]["PartCategory"];
            changed: boolean;
            before: string;
            after: string;
            price_delta_cny?: components["schemas"]["Money"] | null;
        };
        BuildDiff: {
            /** @constant */
            schema_version: 1;
            from_version: number;
            to_version: number;
            lines: components["schemas"]["DiffLine"][];
            /** @description 目标版本合计减来源版本合计。 */
            total_delta_cny: components["schemas"]["Money"];
            /** @description 目标版本预算减来源版本预算。 */
            budget_delta_cny?: components["schemas"]["Money"];
            snapshot_warning?: string;
        };
        Share: {
            /** @constant */
            schema_version: 1;
            /** Format: uuid */
            id: string;
            version: number;
            token: string;
            /** Format: uri */
            url: string;
            /** Format: date-time */
            created_at: string;
            revoked_at: string | null;
        };
        ShareRecord: {
            /** @constant */
            schema_version: 1;
            /** Format: uuid */
            id: string;
            version: number;
            /** Format: date-time */
            created_at: string;
            revoked_at: string | null;
        };
        PublicRequirementSummary: {
            budget_cny: components["schemas"]["Money"];
            budget_flex_percent: number;
            use_case: {
                /** @enum {string} */
                type: "gaming" | "productivity" | "general";
                titles: string[];
                resolution: ("1080p" | "2K" | "4K") | null;
                fps_target: number | null;
            };
            /** @enum {string} */
            size_pref: "atx" | "matx" | "itx" | "any";
            /** @enum {string} */
            noise_pref: "silent" | "normal" | "any";
            brand_pref: {
                /** @enum {string} */
                cpu: "any" | "intel" | "amd";
                /** @enum {string} */
                gpu: "any" | "nvidia" | "amd";
            };
            existing_parts: components["schemas"]["PartCategory"][];
            priority: components["schemas"]["PartCategory"][];
        };
        PublicBuildSummary: {
            /** @constant */
            schema_version: 1;
            version: number;
            parent_version?: number | null;
            intent_label: string;
            total_cny: components["schemas"]["Money"];
            /** Format: date */
            snapshot_date: string;
            price_freshness?: components["schemas"]["PriceFreshness"];
            /** @enum {string} */
            overall_status: "pass" | "review" | "fail";
            /** Format: date-time */
            created_at: string;
        };
        PublicValidationCheck: {
            rule_id: string;
            /** @enum {string} */
            outcome: "pass" | "fail" | "unknown";
            /** @enum {string} */
            severity: "none" | "warning" | "error";
            missing_fields: string[];
            detail: string;
        };
        /** @description 独立最小披露 DTO;不含 notes、observed、session/user/chat/run/内部 build id。 */
        PublicBuildView: {
            /** @constant */
            schema_version: 1;
            summary: components["schemas"]["PublicBuildSummary"];
            requirement: components["schemas"]["PublicRequirementSummary"];
            parts: components["schemas"]["PartLine"][];
            quote: components["schemas"]["Quote"];
            validation: {
                /** @enum {string} */
                overall_status: "pass" | "review" | "fail";
                checks: components["schemas"]["PublicValidationCheck"][];
            };
            disclaimers: string[];
            share: {
                /** Format: date-time */
                created_at: string;
            };
        };
    };
    responses: {
        /** @description RFC problem details;404 同时用于不存在与无权访问 */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
        SessionID: string;
        RunID: string;
        Version: number;
        ShareToken: string;
        ShareID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 进程存活 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 完整依赖可用 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description 未就绪或处于降级状态 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    getAuthState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前身份；未启用或未登录也返回 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    registerAccount: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 注册成功并设置服务端认证会话 Cookie */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    loginAccount: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    logoutAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已退出 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    updateAccountProfile: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            /** @description 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    changeAccountPassword: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description 密码已修改，当前会话已替换 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前匿名用户的会话 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        schema_version: 1;
                        sessions: components["schemas"]["SessionSummary"][];
                    };
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话已创建;必要时同时设置匿名身份 cookie */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话详情、消息、待确认需求和活动 run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    createMessageRun: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @constant */
                    schema_version: 1;
                    text: string;
                };
            };
        };
        responses: {
            /** @description 幂等命中已完成的同一 run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description run 已开始或幂等命中运行中的 run */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    replacePendingRequirement: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequirementSpec"];
            };
        };
        responses: {
            /** @description 严格校验并保存后的需求 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementSpec"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    confirmRequirement: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 幂等命中已完成 run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description build run 已开始 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前匿名用户所属 run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    getRunFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前反馈；未提交时为 null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    submitRunFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackInput"];
            };
        };
        responses: {
            /** @description 反馈已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description SSE 重连游标;从其后一条事件开始。 */
                "Last-Event-ID"?: string;
            };
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 事件细节见 SSE事件协议.md */
            200: {
                headers: {
                    "Cache-Control"?: "no-cache";
                    "X-Accel-Buffering"?: "no";
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    listBuilds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本树摘要,按 version 升序 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        schema_version: 1;
                        builds: components["schemas"]["BuildSummary"][];
                    };
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    getBuild: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 聚合配置读模型 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildView"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    getBuildDiff: {
        parameters: {
            query: {
                from: number;
                to: number;
            };
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 两版本逐品类 diff */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildDiff"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    exportBuildMarkdown: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 与 cmd/builds 共用 presenter 的 Markdown */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown; charset=utf-8": string;
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    listBuildShares: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 包含活动和已撤销记录;不返回 token 或 URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        schema_version: 1;
                        shares: components["schemas"]["ShareRecord"][];
                    };
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    createBuildShare: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 相同幂等键的既有分享 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Share"];
                };
            };
            /** @description 新分享;原始 token 只在响应和 URL 中出现 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Share"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    revokeBuildShareById: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
                share_id: components["parameters"]["ShareID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已撤销;重复撤销保持幂等 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    revokeBuildShare: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已撤销;重复撤销保持幂等 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    getPublicBuildShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 不含会话、用户、聊天与内部 ID 的公开配置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicBuildView"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    exportPublicBuildShareMarkdown: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 与所有者导出和 cmd/builds 共用 presenter */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown; charset=utf-8": string;
                };
            };
            404: components["responses"]["Problem"];
        };
    };
}
