/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 检查 API 进程存活 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 检查完整依赖就绪状态 */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取账号功能与当前登录状态 */
        get: operations["getAuthState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 邮箱密码注册并认领当前匿名数据 */
        post: operations["registerAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 邮箱密码登录并认领当前匿名数据 */
        post: operations["loginAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退出登录并旋转匿名身份 */
        post: operations["logoutAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新显示名称 */
        patch: operations["updateAccountProfile"];
        trace?: never;
    };
    "/api/v1/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 校验当前密码后修改密码 */
        post: operations["changeAccountPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出当前匿名用户的会话 */
        get: operations["listSessions"];
        put?: never;
        /** 创建匿名产品会话 */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        /** 读取一个产品会话 */
        get: operations["getSession"];
        put?: never;
        post?: never;
        /** 永久删除自己的对话及消息、配置版本、分享；运行中返回 409 */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        /** 重命名或归档/恢复自己的对话，不触发模型运行 */
        patch: operations["updateSession"];
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发送消息并启动初筛或改单 run */
        post: operations["createMessageRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/requirement-state": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 增量编辑当前会话需求
         * @description 独立原子草稿编辑事务:复用共享 Reducer、权限与幂等约束,按
         *     expected_revision 防止覆盖并发修改;只更新草稿 RequirementState 与
         *     revision,不创建 AgentRun、不改变 phase。Builder 运行期间同样可用
         *     (运行中的 Builder 只读取启动时冻结的快照;确认快照与历史配置不变)。
         *     生成中确认/生成请求仍被服务端硬拒绝;编辑后以响应中的三轴状态为准。
         */
        patch: operations["updateRequirementState"];
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/requirement": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 完整替换待确认需求
         * @description 只允许 requirement_ready;请求体为完整替换而非 merge patch。
         */
        patch: operations["replacePendingRequirement"];
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/requirement/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 确认需求并启动生成 run(唯一 Builder admission)
         * @description 唯一的原子 confirm-and-start 入口:同一事务校验 readiness/revision/核定
         *     预览 hash,冻结不可变确认快照(review_spec + review_hash)与本 run 的完整
         *     Builder 执行载荷(builder_input_payload + builder_input_hash),并创建唯一
         *     build run。聊天文字、模型 signal、旧 phase 或恢复路径都不能替代本入口。
         *     幂等:相同 Idempotency-Key + 相同请求体重放返回原 run;相同 key 不同请求
         *     返回 409。retry_of_run_id 仅用于失败重试:目标必须属于本会话、kind=build
         *     且已失败,其确认快照的 review_hash 仍与当前核定预览一致;重试复用快照,选型上下文(需求状态、基线草稿、上一提案)整体继承目标 run
         *     的冻结载荷,仅替换本轮 run 标识并另冻新载荷与新 hash。
         */
        post: operations["confirmRequirement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 请求取消当前运行
         * @description 对 running 状态的 run 置位取消标志并取消服务端执行;幂等,重复调用返回当前状态。
         *     取消成功后 run 终态为 interrupted,会话立即恢复可用;run 已终态时为无操作。
         *     SSE 侧随后发出 run.cancelled 与 run.completed(interrupted)。
         */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /** 读取后台 run 状态 */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /** 读取自己的运行反馈 */
        get: operations["getRunFeedback"];
        put?: never;
        /**
         * 提交或修改已结束运行的负反馈
         * @description 同一运行只保留一份反馈；相同内容重复提交不重复创建，修改原因不更换证据。反馈不等于已批准的评估标准答案。
         */
        post: operations["submitRunFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: {
                /** @description SSE 重连游标;从其后一条事件开始。 */
                "Last-Event-ID"?: string;
            };
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        /** 订阅并重放 run 事件 */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/builds": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        /** 列出会话的配置版本 */
        get: operations["listBuilds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/builds/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        /** 读取聚合配置版本 */
        get: operations["getBuild"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/diff": {
        parameters: {
            query: {
                from: number;
                to: number;
            };
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        /** 比较任意两个配置版本 */
        get: operations["getBuildDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/builds/{version}/export.md": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        /** 下载一个版本的 Markdown */
        get: operations["exportBuildMarkdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/builds/{version}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        /** 列出当前用户对固定版本创建过的分享 */
        get: operations["listBuildShares"];
        put?: never;
        /** 创建固定版本的只读分享 */
        post: operations["createBuildShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/builds/{version}/shares/{share_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
                share_id: components["parameters"]["ShareID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 按所有者分享 ID 撤销旧链接 */
        delete: operations["revokeBuildShareById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shares/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 撤销当前用户拥有的分享 */
        delete: operations["revokeBuildShare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/shares/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        /** 公开读取一份只读配置 */
        get: operations["getPublicBuildShare"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/shares/{token}/export.md": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        /** 公开下载固定分享版本的 Markdown */
        get: operations["exportPublicBuildShareMarkdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            schema_version: 1;
            /** @constant */
            status: "ok";
        };
        Readiness: {
            /** @constant */
            schema_version: 1;
            /** @enum {string} */
            status: "ready" | "degraded" | "unavailable";
            dependencies: {
                /** @enum {string} */
                postgres: "ok" | "unavailable";
                /** @enum {string} */
                redis: "ok" | "degraded" | "unavailable";
                /** @enum {string} */
                buildsvc: "ok" | "unavailable";
                /** @enum {string} */
                auth?: "ok" | "unavailable";
            };
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
            /** @enum {string} */
            code: "invalid_request" | "not_found" | "session_busy" | "invalid_session_phase" | "schema_validation_failed" | "upstream_unavailable" | "context_expired" | "run_timeout" | "run_interrupted" | "generation_failed" | "events_expired" | "internal_error" | "auth_disabled" | "auth_invalid_credentials" | "auth_email_exists" | "auth_weak_password" | "auth_session_expired" | "auth_unavailable";
            request_id: string;
        } & {
            [key: string]: unknown;
        };
        Account: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** Format: date-time */
            created_at: string;
        };
        AuthState: {
            /** @constant */
            schema_version: 1;
            enabled: boolean;
            authenticated: boolean;
            account: components["schemas"]["Account"] | null;
            claimed_session_count: number;
        };
        RegisterRequest: {
            /** @constant */
            schema_version: 1;
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
        };
        LoginRequest: {
            /** @constant */
            schema_version: 1;
            /** Format: email */
            email: string;
            password: string;
        };
        ProfileRequest: {
            /** @constant */
            schema_version: 1;
            display_name: string;
        };
        PasswordChangeRequest: {
            /** @constant */
            schema_version: 1;
            current_password: string;
            new_password: string;
            confirm_password: string;
        };
        /** @enum {string} */
        SessionPhase: "collecting" | "requirement_ready" | "building" | "ready" | "changing" | "error";
        SessionSummary: {
            /** @description 服务端提供的细化状态文案；省略时使用阶段名称 */
            status_label?: string;
            /** @constant */
            schema_version: 1;
            id: string;
            title: string;
            /** @description 是否已归档；旧客户端未提供时视为 false */
            archived?: boolean;
            phase: components["schemas"]["SessionPhase"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version_count: number;
        };
        Session: components["schemas"]["SessionSummary"] & {
            messages: components["schemas"]["Message"][];
            proposal?: components["schemas"]["SessionProposal"];
            pending_requirement: components["schemas"]["RequirementSpec"] | null;
            requirement_state: components["schemas"]["RequirementState"] | null;
            /** @description 后端唯一计算的确定性 readiness 真值;前端只渲染。 */
            requirement_readiness: components["schemas"]["RequirementReadiness"] | null;
            /** @description 服务端核定预览(展开有效系统默认后的规范化有效 RequirementSpec v2)。incomplete 时不伪造可确认预览(null)。 */
            review_spec: components["schemas"]["RequirementSpec"] | null;
            /** @description review_spec 的规范化 SHA256;确认请求的 expected_review_hash 必须来自本字段。 */
            review_hash: string | null;
            /** @description 预算上限展示值 = budget_cny ×(1+budget_flex)取整;预算未表达时为 null。生成侧会计使用精确有理数。 */
            effective_budget_ceiling_cny: number | null;
            requirement_confirmation: components["schemas"]["RequirementConfirmation"];
            build_relation: components["schemas"]["BuildRelation"];
            active_run: components["schemas"]["Run"] | null;
            last_error: components["schemas"]["Problem"] | null;
            recovery_phase: ("collecting" | "requirement_ready" | "ready") | null;
            degraded: boolean;
        };
        RequirementReadiness: {
            /** @enum {string} */
            status: "incomplete" | "ready";
            missing_fields: string[];
            blocking_conflicts: string[];
            unsupported_capabilities: string[];
            /** @description 确定性下一步追问(reason_code + 字段组);ready 时为 null。 */
            next_question: {
                reason_code: string;
                fields: string[];
            } | null;
            confirmation_eligible: boolean;
            /** @description 本次预览实际展开的系统默认(origin=system_default);默认规则变化会改变 review_hash。 */
            effective_defaults: {
                field: string;
                value: unknown;
                /** @enum {string} */
                origin: "system_default";
            }[];
        };
        RequirementConfirmation: {
            /**
             * @description confirmed=当前草稿规范化 review_hash 与最近确认快照相同;modified=存在快照但草稿不同或已不足以投影。
             * @enum {string}
             */
            status: "unconfirmed" | "confirmed" | "modified";
            confirmed_revision: number | null;
            confirmed_at: string | null;
            confirmed_review_hash: string | null;
            /**
             * @description 后端按规范化有效字段生成的当前核定预览相对最近确认快照的字段级差异。
             *     已有确认快照且当前草稿可投影时提供(无差异为空数组);无快照、预览
             *     不可投影或快照不可解码时为 null。前端只把字段名和值映射为用户可读
             *     标签,不自行比较 JSON 或重算差异。
             */
            review_diff?: {
                /** @description 需求字段名,与 RequirementState.fields 键一致(含 use_case.* 嵌套路径)。 */
                field: string;
                before: unknown;
                after: unknown;
            }[] | null;
        };
        BuildRelation: {
            /**
             * @description none=从无 build run;running 优先表示活动 Builder;current=最新成功 run 关联当前确认快照且草稿未修改;outdated=已有成功配置但当前确认目标已不同;failed=最近一次 build run 失败(确认快照仍有效,历史成功配置经 version 继续可见)。
             * @enum {string}
             */
            status: "none" | "running" | "current" | "outdated" | "failed";
            /** @description 最新成功 build 的配置版本号;从未成功过为 null。 */
            version: number | null;
            /** @description 关联确认快照 ID(有 build run 时)。 */
            snapshot_id: string | null;
            /** @description 关联确认快照的 review_hash。 */
            review_hash: string | null;
            /** @description 最近(或活动)build run 冻结的完整 Builder 载荷规范化 hash;与实际发送载荷比对即 V5。 */
            builder_input_hash: string | null;
            /**
             * @description 失败重试目标 run ID。仅当最新 build run 已失败(取消中断不算)、确认
             *     仍有效且当前核定预览与该 run 确认快照一致时给出,否则为 null。确认
             *     请求的 retry_of_run_id 必须取本字段;前端无值时不得显示重试 CTA,
             *     也不得从聊天消息、phase 或版本号自行寻找重试目标。
             */
            retry_run_id?: string | null;
        };
        Message: {
            /** @constant */
            schema_version: 1;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "user" | "assistant";
            content: string;
            /** @description 服务端生成的用户可读摘要；展示与复制优先使用非空摘要，原始 content 保留供追溯。 */
            display_content?: string;
            run_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        FeedbackReason: "unnecessary_question" | "requirement_mismatch" | "configuration_issue" | "price_issue" | "unclear_explanation" | "other";
        FeedbackInput: {
            /** @constant */
            schema_version: 1;
            reason: components["schemas"]["FeedbackReason"];
            /** @description 选择 other 时必须填写非空说明 */
            comment?: string;
        };
        Feedback: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            reason: components["schemas"]["FeedbackReason"];
            comment: string;
            fingerprint: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        FeedbackResponse: {
            /** @constant */
            schema_version: 1;
            feedback: components["schemas"]["Feedback"] | null;
        };
        Run: {
            /** @constant */
            schema_version: 1;
            /** Format: uuid */
            id: string;
            session_id: string;
            /** @enum {string} */
            kind: "screening" | "build" | "change";
            /** @enum {string} */
            status: "running" | "succeeded" | "failed" | "interrupted";
            /** Format: date-time */
            started_at: string;
            finished_at?: string | null;
            error?: components["schemas"]["Problem"] | null;
            /** Format: uri-reference */
            events_url: string;
        };
        RequirementSource: {
            /** @enum {string} */
            kind: "chat" | "edit" | "confirmed";
            message_id: string;
            quote: string;
        };
        RequirementField: {
            value?: unknown;
            /** @enum {string} */
            status: "unknown" | "active" | "removed" | "conflict";
            /** @enum {string} */
            kind?: "fact" | "context" | "constraint";
            /** @enum {string} */
            evidence?: "stated" | "uncertain";
            /** @enum {string} */
            strength?: "must" | "prefer";
            /** @enum {string} */
            scope?: "session" | "temporary";
            source?: components["schemas"]["RequirementSource"];
            previous?: components["schemas"]["RequirementField"];
            /**
             * @description 服务端已有件品类与型号的联动来源；用于临时恢复，不接受客户端指定。
             * @enum {string}
             */
            derived_from?: "existing_parts" | "owned_parts";
        };
        RequirementOperation: {
            /** @enum {string} */
            op: "set" | "remove" | "restore" | "alternative" | "conflict";
            /** @description 需求字段路径;保留键 unsupported.monitor|keyboard|mouse 仅接受携带本轮证据的 remove */
            field: string;
            value?: unknown;
            /** @enum {string} */
            strength?: "must" | "prefer";
            /** @enum {string} */
            scope?: "session" | "temporary";
            quote?: string;
            /**
             * @description 新增或替换的 context 背景信息仅允许写入 notes、recipient 或 free.*，不能作为预算等固定执行字段；历史读取保持兼容。
             * @enum {string}
             */
            kind?: "fact" | "context" | "constraint";
            /** @enum {string} */
            evidence?: "stated" | "uncertain" | "inferred";
        };
        RequirementAlternative: {
            field: string;
            value: unknown;
            /** @enum {string} */
            strength: "must" | "prefer";
            /** @enum {string} */
            scope: "session" | "temporary";
            source: components["schemas"]["RequirementSource"];
            /** @enum {string} */
            kind?: "fact" | "context" | "constraint";
        };
        /** @description 未能可靠结构化的本轮原文；不代表用户明确约束，解决后不进入生成或下一轮理解。 */
        RequirementObservation: {
            field?: string;
            text: string;
            reason: string;
            source: components["schemas"]["RequirementSource"];
            resolved?: boolean;
        };
        RequirementChange: {
            revision: number;
            /** @enum {string} */
            op: "set" | "remove" | "restore" | "alternative" | "conflict";
            /** @description 需求字段路径;保留键 unsupported.monitor|keyboard|mouse 仅接受携带本轮证据的 remove */
            field: string;
            before?: components["schemas"]["RequirementField"];
            after?: components["schemas"]["RequirementField"];
            source: components["schemas"]["RequirementSource"];
        };
        /** @description 仅当前装机会话的需求真值(v2；不持久化 reply/next_action，模型动作无状态权威；v1 由解码边界稳定拒绝)；未知、撤销、冲突字段不被程序默认值覆盖；临时例外可恢复之前的字段。备选讨论不改变当前有效需求。readiness/投影/追问计划的唯一实现见 internal/schemas/requirement_readiness.go。 */
        RequirementState: {
            /** @constant */
            schema_version: 2;
            revision: number;
            fields: {
                [key: string]: components["schemas"]["RequirementField"];
            };
            alternatives: components["schemas"]["RequirementAlternative"][];
            changes: components["schemas"]["RequirementChange"][];
            history: components["schemas"]["RequirementChange"][];
            observations?: components["schemas"]["RequirementObservation"][];
        };
        /**
         * @description 确认事务冻结的完整 Builder 执行载荷。字段在确认时全部确定(run ID、
         *     基线草稿、上一提案、有效选型约束);发送路径只读该载荷,不再用会话草稿
         *     或最新 build 重组。规范化 hash 记录为 run 的 builder_input_hash。
         *     requirement_state 仅保留用户事实与溯源;有效选型约束以
         *     effective_constraints 为准(Builder 的模型输入与确定性门槛都读取它)。
         */
        PlanningInput: {
            /** @constant */
            schema_version: 2;
            requirement_state: components["schemas"]["RequirementState"];
            /** @description 确认事务冻结的有效选型约束;失败重试整体继承目标 run 的该字段,仅替换 run 标识。null 仅为历史归档/评估回放兼容。 */
            effective_constraints?: {
                /** @description 确认时冻结的完整核定预览(展开系统默认后的规范化有效 RequirementSpec v2)。 */
                spec: components["schemas"]["RequirementSpec"];
                /** @description 被展开的系统默认及来源(origin=system_default);冻结后修改默认规则不改变旧 run 的执行语义。 */
                defaults: {
                    field: string;
                    value: unknown;
                    /** @enum {string} */
                    origin: "system_default";
                }[];
            } | null;
            base_draft?: {
                [key: string]: unknown;
            };
            previous_proposal?: {
                [key: string]: unknown;
            };
            /**
             * Format: uuid
             * @description 本轮产品侧 run
             */
            run_id?: string;
            /**
             * Format: uuid
             * @description 上一轮 proposal 的 run
             */
            previous_run_id?: string;
        };
        PlanningEvidence: {
            id: string;
            url: string;
            title: string;
            text: string;
            captured_at: string;
            kind: string;
            /** @description 关联的配件编号；历史记录可能缺失 */
            candidate_id?: string;
            /** @description 资料对应的规格或价格字段 */
            field?: string;
            /** @description 实际最终导航地址，历史证据可能缺失 */
            final_url?: string;
            /**
             * @description 本次正文读取方式
             * @enum {string}
             */
            reader?: "http" | "browser";
            /** @description 实际最终页面状态码 */
            http_status?: number;
            /** @description 客户端消费的响应正文大小，不等于浏览器外网流量 */
            read_bytes?: number;
        };
        /** @description 会话候选快照。本地候选可含已读取正文支持的缺失规格补充，external仍为false且保留本地报价；field_evidence关联具体字段来源，不代表全局商品已更新。 */
        PlanningCandidate: {
            id: string;
            category: components["schemas"]["PartCategory"];
            brand: string;
            model: string;
            specs: {
                [key: string]: unknown;
            };
            price_cny: string | null;
            evidence: string[];
            field_evidence?: {
                [key: string]: string;
            };
            field_quotes?: {
                [key: string]: string;
            };
            attributes?: {
                [key: string]: unknown;
            };
            merchant?: string;
            currency?: string;
            price_observed_at?: string;
            unknown?: string[];
            external: boolean;
        };
        PlanningResult: {
            /** @constant */
            schema_version: 1;
            /** @enum {string} */
            outcome: "collect" | "clarify" | "proposal" | "ready" | "technical_fault" | "interrupted";
            /** @description 模型原始意图，不是服务端交付结论 */
            model_outcome?: string;
            /** @description 原子保存后关联的正式版本 */
            build_version?: number;
            delivery?: {
                /** @enum {string} */
                status: "not_applicable" | "unresolved" | "eligible" | "delivered" | "stale";
                issues: string[];
            };
            reply: string;
            draft?: {
                [key: string]: unknown;
            };
            assessments?: {
                field: string;
                /** @enum {string} */
                status: "met" | "unmet" | "unknown";
                explanation: string;
                evidence: string[];
            }[];
            issues: string[];
            assumptions: string[];
            candidates: components["schemas"]["PlanningCandidate"][];
            evidence: components["schemas"]["PlanningEvidence"][];
            validation?: components["schemas"]["ValidationReport"];
            quote?: {
                total_cny: string;
                missing_count: number;
                snapshot_date: string;
                /**
                 * Format: int64
                 * @description 不可变价格批次编号，旧记录可缺省
                 */
                snapshot_id?: number;
            };
            model_calls?: number;
            tool_calls?: number;
            search_calls?: number;
            search_requests?: number;
            page_calls?: number;
            /** @description 实际物理读取次数，含失败；自动升级可产生两次，证据续读不产生请求 */
            read_attempts?: {
                /** @enum {string} */
                method: "http" | "browser";
                duration_ms: number;
                bytes: number;
                status: number;
                outcome: string;
            }[];
            tokens?: number;
            duration_ms?: number;
            stage_ms?: {
                [key: string]: number;
            };
            /** @description 生成服务回传的模型身份(不含部署密钥);旧记录可缺省 */
            builder?: {
                provider: string;
                role: string;
                model: string;
            };
            /**
             * Format: int64
             * @description 本轮使用的目录价格快照;缺省为未知
             */
            catalog_snapshot_id?: number;
        };
        SavedPlanningAssessment: {
            field: string;
            /** @enum {string} */
            status: "met" | "unmet" | "unknown";
            explanation: string;
            evidence: string[];
        };
        SessionProposal: {
            id: number;
            requirement: components["schemas"]["PlanningInput"];
            parent_version: number;
            created_at: string;
            result: components["schemas"]["PlanningResult"];
        };
        RequirementSpec: {
            /** @constant */
            schema_version: 2;
            budget_cny: number;
            /** @default 0.1 */
            budget_flex: number;
            /**
             * @description 产品能力边界(系统默认注入,非用户陈述);当前仅支持 tower,显示器/键鼠按 unsupported observation 阻塞确认。
             * @default [
             *       "tower"
             *     ]
             */
            configuration_scope: "tower"[];
            use_case: {
                /** @enum {string} */
                type: "gaming" | "productivity" | "general";
                /**
                 * @description 元素 trim 后非空
                 * @default []
                 */
                titles: string[];
                /**
                 * @description any 仅是 RequirementState 的有证据用户值;gaming 组合校验拒绝 any
                 * @enum {string}
                 */
                resolution?: "1080p" | "2K" | "4K" | "any";
                /**
                 * @description 仅 gaming 未明确时使用系统默认 balanced
                 * @default balanced
                 * @enum {string}
                 */
                performance_goal: "balanced" | "fps_first" | "quality_first";
                fps_target?: number;
            } & unknown;
            /**
             * @default any
             * @enum {string}
             */
            size_pref: "atx" | "matx" | "itx" | "any";
            /**
             * @default any
             * @enum {string}
             */
            noise_pref: "silent" | "normal" | "any";
            brand_pref?: {
                /**
                 * @default any
                 * @enum {string}
                 */
                cpu: "any" | "intel" | "amd";
                /**
                 * @default any
                 * @enum {string}
                 */
                gpu: "any" | "nvidia" | "amd";
            };
            /** @default [] */
            existing_parts: components["schemas"]["PartCategory"][];
            /**
             * @description 有已有件时必须明确；新增购买费用或整机参考总价。
             * @enum {string}
             */
            budget_basis?: "new_purchase" | "full_build";
            /** @description 每品类一个准确型号；仅 SSD 可多件，其余数量为 1。程序执行前精确绑定并锁定。 */
            owned_parts?: {
                category: components["schemas"]["PartCategory"];
                model: string;
                /** @default 1 */
                quantity: number;
            }[];
            /** @default [] */
            priority: components["schemas"]["PartCategory"][];
            /** @default  */
            notes: string;
            /** @description 当前有效字段的明确强度，键采用 brand_pref.cpu、size_pref 等需求字段路径；缺失时兼容旧需求语义，不据此认定为用户已表达。 */
            constraint_strengths?: {
                [key: string]: "must" | "prefer";
            };
            /** @description 用途事实、补充说明或配置条件。must 强度不把事实和说明变成需要目录证明的商品硬条件；旧记录缺少分类时保持未知。 */
            requirement_semantics?: {
                [key: string]: "fact" | "context" | "constraint";
            };
            /** @description 尚未解决的原文及来源，用于理解用途和后续必要确认，不能冒充已核验硬条件。 */
            requirement_observations?: components["schemas"]["RequirementObservation"][];
            /** @description 当前会话的有效外观、装机对象与 free.* 用户事实；不含已撤销信息、备选方案或长期画像。 */
            requirement_details?: {
                appearance?: string;
                recipient?: string;
            } & {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        PartCategory: "cpu" | "gpu" | "motherboard" | "memory" | "ssd" | "psu" | "case" | "cooler";
        /** @example 6419.90 */
        Money: string;
        /**
         * @description 按响应时间动态计算；0–7 天 fresh，8–14 天 aging，超过 14 天 stale，缺少观察关联为 unknown。
         * @enum {string}
         */
        PriceFreshness: "fresh" | "aging" | "stale" | "unknown";
        PriceFreshnessSummary: {
            overall: components["schemas"]["PriceFreshness"];
            oldest_observed_date?: string | null;
            max_age_days?: number | null;
            fresh_count: number;
            aging_count: number;
            stale_count: number;
            unknown_count: number;
        };
        BuildSummary: {
            /** @constant */
            schema_version: 1;
            version: number;
            parent_version?: number | null;
            intent: string;
            total_cny: components["schemas"]["Money"];
            /** Format: date */
            snapshot_date: string;
            price_freshness?: components["schemas"]["PriceFreshness"];
            /** @enum {string} */
            overall_status: "pass" | "review" | "fail";
            /** Format: date-time */
            created_at: string;
        };
        PartLine: {
            /** @description 用户已有，无需购买；该行价格仍为参考价。 */
            owned?: boolean;
            category: components["schemas"]["PartCategory"];
            sku: string;
            name: string;
            quantity: number;
            unit_price_cny?: components["schemas"]["Money"] | null;
            subtotal_cny?: components["schemas"]["Money"] | null;
            rationale?: string;
            /** Format: date */
            price_observed_date?: string;
            price_freshness?: components["schemas"]["PriceFreshness"];
            /** @enum {string} */
            price_availability_basis?: "confirmed_stock" | "search_listing" | "unknown";
        };
        ValidationCheck: {
            rule_id: string;
            /** @enum {string} */
            outcome: "pass" | "fail" | "unknown";
            /** @enum {string} */
            severity: "none" | "warning" | "error";
            observed: {
                [key: string]: unknown;
            };
            missing_fields: string[];
            detail: string;
        };
        ValidationReport: {
            /** @enum {string} */
            overall_status: "pass" | "review" | "fail";
            checks: components["schemas"]["ValidationCheck"][];
        };
        Quote: {
            /**
             * Format: int64
             * @description 不可变价格批次编号，旧记录可缺省
             */
            snapshot_id?: number;
            budget_known?: boolean;
            purchase_total_cny?: components["schemas"]["Money"];
            /** @enum {string} */
            budget_basis?: "new_purchase" | "full_build";
            /** Format: date */
            snapshot_date: string;
            total_cny: components["schemas"]["Money"];
            budget_cny: components["schemas"]["Money"];
            /** @description 预算减配置合计;正数表示剩余预算。 */
            budget_delta_cny: components["schemas"]["Money"];
            missing_count: number;
            missing_skus: string[];
            price_freshness?: components["schemas"]["PriceFreshnessSummary"];
        };
        BuildView: {
            candidate_snapshot?: {
                candidates?: components["schemas"]["PlanningCandidate"][];
                evidence?: components["schemas"]["PlanningEvidence"][];
                assessments?: components["schemas"]["SavedPlanningAssessment"][];
                assumptions?: string[];
                reply?: string;
            };
            /** @constant */
            schema_version: 1;
            summary: components["schemas"]["BuildSummary"];
            requirement: components["schemas"]["RequirementSpec"] | components["schemas"]["PlanningInput"];
            parts: components["schemas"]["PartLine"][];
            quote: components["schemas"]["Quote"];
            validation: components["schemas"]["ValidationReport"];
            disclaimers: string[];
        };
        DiffLine: {
            category: components["schemas"]["PartCategory"];
            changed: boolean;
            before: string;
            after: string;
            price_delta_cny?: components["schemas"]["Money"] | null;
        };
        BuildDiff: {
            /** @constant */
            schema_version: 1;
            from_version: number;
            to_version: number;
            lines: components["schemas"]["DiffLine"][];
            /** @description 目标版本合计减来源版本合计。 */
            total_delta_cny: components["schemas"]["Money"];
            /** @description 目标版本预算减来源版本预算。 */
            budget_delta_cny?: components["schemas"]["Money"];
            snapshot_warning?: string;
        };
        Share: {
            /** @constant */
            schema_version: 1;
            /** Format: uuid */
            id: string;
            version: number;
            token: string;
            /** Format: uri */
            url: string;
            /** Format: date-time */
            created_at: string;
            revoked_at: string | null;
        };
        ShareRecord: {
            /** @constant */
            schema_version: 1;
            /** Format: uuid */
            id: string;
            version: number;
            /** Format: date-time */
            created_at: string;
            revoked_at: string | null;
        };
        PublicRequirementSummary: {
            known_fields?: string[];
            budget_cny: components["schemas"]["Money"];
            budget_flex_percent: number;
            use_case: {
                /** @enum {string} */
                type: "gaming" | "productivity" | "general" | "unknown";
                titles: string[];
                resolution: ("1080p" | "2K" | "4K") | null;
                fps_target: number | null;
            };
            /** @enum {string} */
            size_pref: "atx" | "matx" | "itx" | "any" | "unknown";
            /** @enum {string} */
            noise_pref: "silent" | "normal" | "any" | "unknown";
            brand_pref: {
                /** @enum {string} */
                cpu: "any" | "intel" | "amd" | "unknown";
                /** @enum {string} */
                gpu: "any" | "nvidia" | "amd" | "unknown";
            };
            existing_parts: components["schemas"]["PartCategory"][];
            priority: components["schemas"]["PartCategory"][];
        };
        PublicBuildSummary: {
            /** @constant */
            schema_version: 1;
            version: number;
            parent_version?: number | null;
            intent_label: string;
            total_cny: components["schemas"]["Money"];
            /** Format: date */
            snapshot_date: string;
            price_freshness?: components["schemas"]["PriceFreshness"];
            /** @enum {string} */
            overall_status: "pass" | "review" | "fail";
            /** Format: date-time */
            created_at: string;
        };
        PublicValidationCheck: {
            rule_id: string;
            /** @enum {string} */
            outcome: "pass" | "fail" | "unknown";
            /** @enum {string} */
            severity: "none" | "warning" | "error";
            missing_fields: string[];
            detail: string;
        };
        /** @description 独立最小披露 DTO;不含 notes、observed、session/user/chat/run/内部 build id。 */
        PublicBuildView: {
            sources?: {
                url: string;
                title: string;
                captured_at: string;
            }[];
            /** @constant */
            schema_version: 1;
            summary: components["schemas"]["PublicBuildSummary"];
            requirement: components["schemas"]["PublicRequirementSummary"];
            parts: components["schemas"]["PartLine"][];
            quote: components["schemas"]["Quote"];
            validation: {
                /** @enum {string} */
                overall_status: "pass" | "review" | "fail";
                checks: components["schemas"]["PublicValidationCheck"][];
            };
            disclaimers: string[];
            share: {
                /** Format: date-time */
                created_at: string;
            };
        };
    };
    responses: {
        /** @description RFC problem details;404 同时用于不存在与无权访问 */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
        SessionID: string;
        RunID: string;
        Version: number;
        ShareToken: string;
        ShareID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 进程存活 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 完整依赖可用 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description 未就绪或处于降级状态 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    getAuthState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前身份；未启用或未登录也返回 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    registerAccount: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 注册成功并设置服务端认证会话 Cookie */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    loginAccount: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    logoutAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已退出 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    updateAccountProfile: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            /** @description 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    changeAccountPassword: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description 密码已修改，当前会话已替换 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                /** @description true 仅列出已归档会话，默认仅列出未归档会话。 */
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前匿名用户的会话 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        schema_version: 1;
                        sessions: components["schemas"]["SessionSummary"][];
                    };
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话已创建;必要时同时设置匿名身份 cookie */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话详情、消息、待确认需求和活动 run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    archived?: boolean;
                };
            };
        };
        responses: {
            /** @description 更新后的会话 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    createMessageRun: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @constant */
                    schema_version: 1;
                    text: string;
                };
            };
        };
        responses: {
            /** @description 幂等命中已完成的同一 run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description run 已开始或幂等命中运行中的 run */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    updateRequirementState: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expected_revision: number;
                    operations: components["schemas"]["RequirementOperation"][];
                };
            };
        };
        responses: {
            /** @description 保存后的完整会话真值 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description 需求版本已变化或会话正在执行任务，需重新读取会话 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    replacePendingRequirement: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequirementSpec"];
            };
        };
        responses: {
            /** @description 严格校验并保存后的需求 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementSpec"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    confirmRequirement: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @constant */
                    schema_version: 2;
                    /** @description 用户打开核定面板时看到的草稿修订号。 */
                    expected_revision: number;
                    /** @description 来自最新服务端核定预览(session DTO 的 review_hash)。revision 不变但默认规则/配置范围变化时该 hash 也会变化。 */
                    expected_review_hash: string;
                    /** @description 仅失败重试时传目标 build run ID;省略表示新确认。 */
                    retry_of_run_id?: string | null;
                };
            };
        };
        responses: {
            /** @description 幂等命中已完成 run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description build run 已开始 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /**
             * @description revision 变化(requirement_revision_conflict)、核定预览失效
             *     (requirement_review_conflict,含默认/配置范围变化)、存在活动运行
             *     (session_busy)、重试目标无效(invalid_retry_target)或幂等冲突。
             *     返回最新会话供用户重新核定。
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description readiness 不完整(requirement_not_ready),响应 detail 指向 requirement_readiness。 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取消请求已受理(或 run 已终态,原样返回) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前匿名用户所属 run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    getRunFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前反馈；未提交时为 null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    submitRunFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackInput"];
            };
        };
        responses: {
            /** @description 反馈已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description SSE 重连游标;从其后一条事件开始。 */
                "Last-Event-ID"?: string;
            };
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 事件细节见 SSE事件协议.md */
            200: {
                headers: {
                    "Cache-Control"?: "no-cache";
                    "X-Accel-Buffering"?: "no";
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    listBuilds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本树摘要,按 version 升序 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        schema_version: 1;
                        builds: components["schemas"]["BuildSummary"][];
                    };
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    getBuild: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 聚合配置读模型 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildView"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    getBuildDiff: {
        parameters: {
            query: {
                from: number;
                to: number;
            };
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 两版本逐品类 diff */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildDiff"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    exportBuildMarkdown: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 与 cmd/builds 共用 presenter 的 Markdown */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown; charset=utf-8": string;
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    listBuildShares: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 包含活动和已撤销记录;不返回 token 或 URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        schema_version: 1;
                        shares: components["schemas"]["ShareRecord"][];
                    };
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    createBuildShare: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 相同幂等键的既有分享 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Share"];
                };
            };
            /** @description 新分享;原始 token 只在响应和 URL 中出现 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Share"];
                };
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    revokeBuildShareById: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionID"];
                version: components["parameters"]["Version"];
                share_id: components["parameters"]["ShareID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已撤销;重复撤销保持幂等 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    revokeBuildShare: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已撤销;重复撤销保持幂等 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Problem"];
        };
    };
    getPublicBuildShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 不含会话、用户、聊天与内部 ID 的公开配置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicBuildView"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    exportPublicBuildShareMarkdown: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 与所有者导出和 cmd/builds 共用 presenter */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown; charset=utf-8": string;
                };
            };
            404: components["responses"]["Problem"];
        };
    };
}
