import { expect, test } from "@playwright/test";
import type { Session } from "../src/lib/api/types";

test("tool-backed proposals remain editable, refreshable and separate from confirmed versions", async ({ page }, testInfo) => {
  await page.goto("/");
  await page.getByLabel("输入需求或改单内容").fill("预算 6000，主要剪 4K 视频，尽量安静");
  await page.getByRole("button", { name: "发送", exact: true }).click();
  await page.waitForURL(/\/s\/[^/]+$/);
  const id = new URL(page.url()).pathname.split("/").at(-1)!;
  const snapshot = async (): Promise<Session> => (await page.request.get(`/api/v1/sessions/${id}`)).json();
  await expect.poll(async () => (await snapshot()).phase).toBe("requirement_ready");
  await page.getByRole("button", { name: "查看 / 修改", exact: true }).click();
  const panel = page.getByRole("region", { name: "当前需求", exact: true });
  await panel.getByRole("button", { name: "修改预算", exact: true }).click();
  await panel.getByLabel("编辑预算", { exact: true }).fill("12000");
  await panel.getByRole("button", { name: "保存需求", exact: true }).click();
  await expect.poll(async () => (await snapshot()).requirement_state!.fields.noise_pref.strength).toBe("prefer");
  await panel.getByRole("button", { name: "确认并开始选配", exact: true }).click();
  await expect.poll(async () => (await snapshot()).version_count).toBe(1);
  const delivered = (await snapshot()).proposal!.result;
  expect(delivered.model_outcome).toBe("proposal");
  expect(delivered.delivery?.status).toBe("delivered");
  expect(delivered.build_version).toBe(1);
  expect(delivered.issues).toEqual([]);
  expect(delivered.quote?.snapshot_date).toBe("2026-07-28");
  if (testInfo.project.name === "desktop") await expect(page.getByRole("region", { name: "配置检查器", exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("automatic-delivery.png") });
  const firstBuild = await (await page.request.get(`/api/v1/sessions/${id}/builds/1`)).json();
  const shareResponse = await page.request.post(`/api/v1/sessions/${id}/builds/1/shares`, { headers: { "Idempotency-Key": crypto.randomUUID() } });
  expect(shareResponse.ok()).toBeTruthy();
  const share = await shareResponse.json();
  const publicResponse = await page.request.get(`/api/v1/public/shares/${share.token}`);
  expect(publicResponse.ok()).toBeTruthy();
  expect((await publicResponse.json()).requirement.known_fields).toContain("budget_cny");
  const exported = await page.request.get(`/api/v1/public/shares/${share.token}/export.md`);
  expect(exported.ok()).toBeTruthy();
  expect(await exported.text()).toContain("Ryzen 5 5600");
  const publicPage = await page.context().newPage();
  await publicPage.goto(share.url);
  await expect(publicPage.getByRole("heading", { name: "需求摘要", exact: true })).toBeVisible();
  await publicPage.close();
  await page.getByRole("button", { name: "查看 / 修改", exact: true }).click();
  await panel.getByRole("button", { name: "修改静音", exact: true }).click();
  await panel.getByLabel("静音要求强度", { exact: true }).selectOption("must");
  await panel.getByRole("button", { name: "保存需求", exact: true }).click();
  await panel.getByRole("button", { name: "确认修改并继续选配", exact: true }).click();
  await expect.poll(async () => (await snapshot()).proposal?.result.outcome).toBe("proposal");
  const pending = await snapshot();
  expect(pending.phase).not.toBe("error");
  expect(pending.version_count).toBe(1);
  expect(pending.requirement_state!.fields.noise_pref.strength).toBe("must");
  expect(pending.proposal!.result.tool_calls).toBe(2);
  expect(pending.proposal!.result.candidates.length).toBeGreaterThan(0);
  await page.reload();
  await expect(page.getByLabel("输入需求或改单内容")).toBeEnabled();
  expect((await snapshot()).proposal).toEqual(pending.proposal);
  expect(await (await page.request.get(`/api/v1/sessions/${id}/builds/1`)).json()).toEqual(firstBuild);
  if (testInfo.project.name !== "desktop") await page.getByRole("button", { name: "查看配置详情", exact: true }).click();
  await expect(page.getByRole("region", { name: "待解决方案", exact: true })).toBeVisible();
  const proposalPanel = page.getByRole("region", { name: "待解决方案", exact: true });
  await expect(proposalPanel.getByText("本轮未联网，使用本地资料", { exact: true })).toBeVisible();
  await proposalPanel.getByText(/^查看方案来源 ·/).click();
  await proposalPanel.getByText("商品规格与报价资料", { exact: false }).first().click();
  await expect(proposalPanel.getByText(/本地库已有资料 ·/).first()).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("saved-proposal.png") });
  await page.getByRole("button", { name: "已确认配置", exact: true }).click();
  await expect(page.getByText("Ryzen 5 5600", { exact: true }).filter({ visible: true }).first()).toBeVisible();
  if (testInfo.project.name !== "desktop") await page.getByRole("button", { name: "关闭详情", exact: true }).click();
  await page.goto(`/s/${id}?version=1`);
  await expect(page.getByLabel("输入需求或改单内容")).toBeEnabled();
  await page.getByLabel("输入需求或改单内容").fill("静音还是尽量满足就好");
  await page.getByRole("button", { name: "发送", exact: true }).click();
  await expect.poll(async () => (await snapshot()).requirement_state!.fields.noise_pref.strength).toBe("prefer");
  await page.getByRole("button", { name: "查看 / 修改", exact: true }).click();
  await panel.getByRole("button", { name: "确认修改并继续选配", exact: true }).click();
  await expect.poll(async () => (await snapshot()).version_count).toBe(2);
  await expect(page).not.toHaveURL(/version=1/);
  expect((await snapshot()).proposal!.result.delivery?.status).toBe("delivered");
  expect(await (await page.request.get(`/api/v1/sessions/${id}/builds/1`)).json()).toEqual(firstBuild);
  await page.reload();
  await expect(page.getByLabel("输入需求或改单内容")).toBeEnabled();
  expect((await snapshot()).version_count).toBe(2);
  await page.getByRole("button", { name: "查看 / 修改", exact: true }).click();
  await panel.getByText("添加其他要求", { exact: true }).click();
  await panel.getByLabel("具体要求", { exact: true }).fill("必须提供两个网口");
  await panel.getByLabel("重要程度", { exact: true }).selectOption("must");
  await panel.getByRole("button", { name: "保存要求", exact: true }).click();
  await expect.poll(async () => Object.entries((await snapshot()).requirement_state!.fields).filter(([key, value]) => key.startsWith("free.") && value.status === "active").length).toBe(1);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
});
