import { expect, test } from "@playwright/test";
import type { Session } from "../src/lib/api/types";

test("a sourced session supplement resolves a saved proposal without rewriting the old version", async ({ page }, testInfo) => {
  await expect.poll(async () => (await page.request.get("/healthz")).status(), { timeout: 60_000 }).toBe(200);
  await page.goto("/");
  const send = async (text: string) => {
    await expect(page.getByLabel("输入需求或改单内容")).toBeEnabled();
    await page.getByLabel("输入需求或改单内容").fill(text);
    await page.getByRole("button", { name: "发送", exact: true }).click();
  };
  await send("预算7000，剪1080p多轨视频，不要求静音");
  await page.waitForURL(/\/s\/[^/]+$/);
  const id = new URL(page.url()).pathname.split("/").at(-1)!;
  const snapshot = async (): Promise<Session> => (await page.request.get(`/api/v1/sessions/${id}`)).json();
  await expect.poll(async () => (await snapshot()).phase).toBe("requirement_ready");
  await page.getByRole("button", { name: "查看 / 修改", exact: true }).click();
  await page.getByRole("button", { name: "确认并开始选配", exact: true }).click();
  await expect.poll(async () => (await snapshot()).version_count).toBe(1);
  const original = await (await page.request.get(`/api/v1/sessions/${id}/builds/1`)).json();
  await send("预算调整为6500，其他要求保留并继续选配");
  await expect.poll(async () => (await snapshot()).version_count).toBe(2);
  const budget = await snapshot();
  expect(budget.requirement_state?.fields.budget_cny.value).toBe(6500);
  expect(budget.requirement_state?.fields["free.workload_resolution"].value).toBe("1080p多轨视频剪辑");
  expect(budget.requirement_state?.fields.noise_pref.status).toBe("removed");
  await send("换成缺规格主板候选继续核实");
  await expect.poll(async () => (await snapshot()).proposal?.result.delivery?.status).toBe("unresolved");
  const pending = await snapshot();
  expect(pending.version_count).toBe(2);
  expect(pending.proposal?.result.issues.length).toBeGreaterThan(0);
  expect(pending.proposal?.result.validation?.checks.find(c => c.rule_id === "MEMORY_SPEED")).toMatchObject({ outcome: "unknown", missing_fields: ["motherboard.memory_speed_max_mts"] });
  expect(pending.proposal?.result.candidates.some(c => c.id === "mb-offline-gap")).toBe(true);
  expect(pending.messages.at(-1)?.content).not.toMatch(/全部兼容|性能保证|已经正式交付/);
  await page.reload();
  await expect(page.getByLabel("输入需求或改单内容")).toBeEnabled();
  expect((await snapshot()).proposal).toEqual(pending.proposal);
  await send("读取资料补齐主板规格并继续校验");
  await expect.poll(async () => (await snapshot()).version_count).toBe(3);
  const completed = await snapshot();
  const result = completed.proposal!.result;
  expect(result.delivery?.status).toBe("delivered");
  expect(result.page_calls).toBe(1); // Offline transport read, zero external requests.
  const candidate = result.candidates.find(c => c.id === "mb-offline-gap")!;
  expect(candidate.external).toBe(false);
  expect(candidate.price_cny).not.toBeNull();
  expect(candidate.specs.memory_speed_max_mts).toBe(3200);
  const source = result.evidence.find(e => e.id === candidate.field_evidence?.memory_speed_max_mts)!;
  expect(source).toMatchObject({ kind: "page", candidate_id: candidate.id, field: "memory_speed_max_mts", url: "https://spec.eval.invalid/motherboard", text: "Memory speed 3200 MT/s" });
  expect(completed.requirement_state?.fields).toEqual(budget.requirement_state?.fields);
  if (testInfo.project.name !== "desktop") await page.getByRole("button", { name: "查看配置详情", exact: true }).click();
  await page.getByRole("button", { name: "选配说明", exact: true }).click();
  await page.getByText(/^查看方案来源 ·/).filter({ visible: true }).click();
  await page.locator("summary").filter({ hasText: "https://spec.eval.invalid/motherboard" }).click();
  await expect(page.getByText(/支持内存频率/).filter({ visible: true }).first()).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("session-specification-evidence.png") });
  if (testInfo.project.name !== "desktop") await page.getByRole("button", { name: "关闭详情", exact: true }).click();
  await page.reload();
  await send("按当前方案继续校验");
  await expect.poll(async () => (await snapshot()).version_count).toBe(4);
  expect((await snapshot()).proposal?.result.page_calls).toBe(0);
  expect(await (await page.request.get(`/api/v1/sessions/${id}/builds/1`)).json()).toEqual(original);
  await page.goto(`/s/${id}?version=1`);
  await page.reload();
  if (testInfo.project.name !== "desktop") await page.getByRole("button", { name: "查看配置详情", exact: true }).click();
  await expect(page.getByText("历史只读", { exact: true }).filter({ visible: true }).first()).toBeVisible();
  expect((await snapshot()).version_count).toBe(4);
  await testInfo.attach("session-supplement-evidence.json", { body: JSON.stringify({ pending, completed, restored: await snapshot(), actual_model_requests: 0, actual_external_requests: 0 }, null, 2), contentType: "application/json" });
});
