import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
import type { Session } from "../src/lib/api/types";

test("recorded video request builds after a soft budget edit and preserves explicit hard failures", async ({ page }, testInfo) => {
  await page.goto("/");
  await page.getByLabel("输入需求或改单内容").fill("预算 6000，主要剪 4K 视频，尽量安静");
  await page.getByRole("button", { name: "发送", exact: true }).click();
  await page.waitForURL(/\/s\/[^/]+$/);
  const sessionID = new URL(page.url()).pathname.split("/").at(-1)!;
  const snapshot = async (): Promise<Session> => (await page.request.get(`/api/v1/sessions/${sessionID}`)).json();
  await expect.poll(async () => (await snapshot()).phase).toBe("requirement_ready");
  await page.getByRole("button", { name: "查看 / 修改", exact: true }).click();
  const panel = page.getByRole("region", { name: "当前需求", exact: true });
  await expect(panel.getByText("¥6,000", { exact: true })).toBeVisible();
  const original = await snapshot();
  expect(original.requirement_state!.fields["use_case.resolution"].status).toBe("unknown");
  expect(original.requirement_state!.fields.budget_flex.status).toBe("unknown");
  await panel.getByText(/保留的原话/).click();
  const observation = panel.getByText("主要剪 4K 视频", { exact: true }).locator("..");
  await expect(observation).toContainText("用户消息：主要剪 4K 视频");
  await observation.getByRole("button", { name: "查看来源消息", exact: true }).click();
  await expect(page.locator("article:focus")).toContainText("预算 6000，主要剪 4K 视频，尽量安静");
  await page.getByRole("button", { name: "查看 / 修改", exact: true }).click();
  await panel.getByRole("button", { name: "修改预算", exact: true }).click();
  await panel.getByLabel("预算要求强度", { exact: true }).selectOption("prefer");
  await panel.getByRole("button", { name: "保存需求", exact: true }).click();
  await expect.poll(async () => (await snapshot()).requirement_state!.fields.budget_cny.strength).toBe("prefer");
  const edited = await snapshot();
  for (const [key, field] of Object.entries(original.requirement_state!.fields)) {
    if (key !== "budget_cny") expect(edited.requirement_state!.fields[key]).toEqual(field);
  }
  await page.screenshot({ path: testInfo.outputPath("video-requirements.png") });
  await panel.getByRole("button", { name: "确认并生成配置", exact: true }).click();
  await expect.poll(async () => (await snapshot()).version_count).toBe(1);
  await expect.poll(async () => (await snapshot()).phase).toBe("ready");
  const built = await snapshot();
  expect(built.confirmed_requirement!.requirement_observations).toEqual(expect.arrayContaining([expect.objectContaining({ text: "主要剪 4K 视频", source: expect.objectContaining({ quote: "主要剪 4K 视频", kind: "chat" }) })]));
  expect(built.confirmed_requirement!.constraint_strengths!.budget_cny).toBe("prefer");
  const firstBuild = await (await page.request.get(`/api/v1/sessions/${sessionID}/builds/1`)).json();
  await page.reload();
  await expect(page.getByRole("region", { name: "会话", exact: true })).toContainText("核心搭配");
  expect((await snapshot()).confirmed_requirement_state).toEqual(built.confirmed_requirement_state);
  await page.screenshot({ path: testInfo.outputPath("video-generated.png") });

  await page.getByRole("button", { name: "查看 / 修改", exact: true }).click();
  await panel.getByRole("button", { name: "修改静音", exact: true }).click();
  await panel.getByLabel("静音要求强度", { exact: true }).selectOption("must");
  await panel.getByRole("button", { name: "保存需求", exact: true }).click();
  await panel.getByRole("button", { name: "确认修改并生成新版本", exact: true }).click();
  await expect.poll(async () => (await snapshot()).phase).toBe("error");
  const failed = await snapshot();
  expect(failed.version_count).toBe(1);
  expect(failed.requirement_state!.fields.noise_pref.strength).toBe("must");
  expect(failed.last_error!.detail).toContain("静音");
  expect(failed.last_error!.detail).toContain("已保存");
  const message = failed.messages.at(-1)!;
  await expect(page.locator(`[id="message-${message.id}"]`)).toContainText("静音");
  await expect(page.locator(`[id="message-${message.id}"]`)).toContainText("已保存");
  await expect(page.getByLabel("输入需求或改单内容")).toBeEnabled();
  await expect(page.getByRole("button", { name: "查看或补充需求", exact: true })).toBeVisible();
  await page.reload();
  await expect(page.locator(`[id="message-${message.id}"]`)).toContainText("静音");
  await expect(page.locator(`[id="message-${message.id}"]`)).not.toContainText("改为尽量满足");
  expect(await (await page.request.get(`/api/v1/sessions/${sessionID}/builds/1`)).json()).toEqual(firstBuild);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  const issues = await new AxeBuilder({ page }).analyze();
  expect(issues.violations.filter((item) => ["serious", "critical"].includes(item.impact ?? ""))).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("hard-condition-reason.png") });

  // A failed build can continue through chat; new budget information does not erase the hard noise requirement.
  await page.getByLabel("输入需求或改单内容").fill("预算改成6000");
  const sent = page.waitForResponse((response) => response.url().endsWith(`/api/v1/sessions/${sessionID}/messages`) && response.request().method() === "POST");
  await page.getByRole("button", { name: "发送", exact: true }).click();
  expect((await sent).status()).toBe(202);
  await expect.poll(async () => (await snapshot()).phase, { timeout: 15_000 }).toBe("requirement_ready");
  expect((await snapshot()).requirement_state!.fields.noise_pref.strength).toBe("must");
  await page.getByRole("button", { name: "查看 / 修改", exact: true }).click();
  await panel.getByText(/尚未说明 ·/).click();
  await panel.getByRole("button", { name: "补充补充说明", exact: true }).click();
  await panel.getByLabel("编辑补充说明", { exact: true }).fill("每天剪 4K 旅行纪录片");
  await panel.getByLabel("补充说明信息用途", { exact: true }).selectOption("context");
  await panel.getByRole("button", { name: "保存需求", exact: true }).click();
  await expect.poll(async () => (await snapshot()).requirement_state!.fields.notes.kind).toBe("context");
  const clarified = await snapshot();
  expect(clarified.requirement_state!.fields.notes.strength).toBe("must");
  expect(clarified.requirement_state!.fields.notes.source!.quote).toContain("补充说明");
  expect(clarified.requirement_state!.fields.notes.source!.quote).not.toContain("必须满足");
  expect(clarified.requirement_state!.observations!.every((item) => item.resolved)).toBeTruthy();
  expect(await (await page.request.get(`/api/v1/sessions/${sessionID}/builds/1`)).json()).toEqual(firstBuild);
  await page.screenshot({ path: testInfo.outputPath("context-edit.png") });
});
